M48
; DRILL file {KiCad 7.0.10} date Monday, January 29, 2024 at 05:08:55 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-01-29T17:08:55-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0394
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0400
%
G90
G05
T1
X3.672Y-3.5008
X3.7778Y-3.5399
T2
X3.9Y-3.0
T3
X4.2Y-3.0
X4.2Y-3.1
X4.2Y-3.2
X4.2Y-3.3
X4.2Y-3.4
X4.2Y-3.5
X4.2Y-3.6
X4.8Y-3.0
X4.8Y-3.1
X4.8Y-3.2
X4.8Y-3.3
X4.8Y-3.4
X4.8Y-3.5
X4.8Y-3.6
M30
